### PR TITLE
Added ctracker data handler demo

### PR DESCRIPTION
**Pull request by etedesco**

### CODE REVIEW

**Comment by etedesco** [comment]
There is a mismatch between the commit message and the Data Handler Project Name. The right name is "ctracker". Sorry!

**Comment by hawkchen** [comment]
it's ok, just modify it and send another pull request. :)

**Comment by etedesco** [comment]
Hi hawkchen, I can't modify the commit message from "Added cracker data handler demo" to "Added ctracker data handler demo" ...or probably I don't know how to do that :). I'm sorry but I'm not so skilled with github

**Comment by hawkchen** [comment]
it's ok. you can just send another pull request, because this pull request is closed, I cannot merge your data attribute handler.

**Comment by etedesco** [comment]
Hi hawkchen. I did. Let me know if I did the right thing. Regards Enrico

**Comment by etedesco** [comment]
Hi hawkchen, thanks a lot for your help. I verified my project under other devices and some background colours should be changed in my CSS file and/or Javascript file. Can I update my project ? And in this case, what is the best way with Github to proceeded ? 
Regards 
Enrico

**Comment by hawkchen** [comment]
I think you can send another pull request after the modification.

**Comment by etedesco** [comment]
Hi Chen, you should see a pull request for my ctracker project.
Let me know if you have any issue about the merge and I will try to help you
Best Regards
Enrico

On Fri, Jan 15, 2016 at 10:08 AM, Hawk Chen notifications@github.com
wrote:

> I think you can send another pull request after the modification.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zkoss/dataAttributeHandlers/pull/5#issuecomment-171907686
> .

## 

Enrico Tedeschini
Via Ippocrate 3
41126 Modena
Italy

**Pull request merged**
