### PR TITLE
Added a new data handler: gauge

### PR DESCRIPTION
**Pull request by windeyu**
Hello, I developed in Eclipse and copied over to my github respository.  Please let me know if I missed any files.

### CODE REVIEW

**Comment by hawkchen** [comment]
Thanks for your submission. Because we merge others' pull requests, there is a conflict in `zk.xml`. Please resolve the conflict and send another pull request again.

**Comment by windeyu** [comment]
Hi Hawk,Believe it or not, it's my first time using the Github.  Let me try to figure out how to update my project from the original source to resolve the conflict.regards,-Edwin 

```
On Monday, January 4, 2016 12:01 AM, Hawk Chen <notifications@github.com> wrote:
```

 Thanks for your submission. Because we merge others' pull requests, there is a conflict in zk.xml. Please resolve the conflict and send another pull request again.—

**Comment by windeyu** [comment]
Hi Hawk,I rebased my local project and saw my change there ok.  Did you resolve the conflict already for me?Thanks.-Edwin

```
On Monday, January 4, 2016 6:29 PM, Edwin Yu <windeyu@yahoo.com> wrote:
```

 Hi Hawk,Believe it or not, it's my first time using the Github.  Let me try to figure out how to update my project from the original source to resolve the conflict.regards,-Edwin 

```
On Monday, January 4, 2016 12:01 AM, Hawk Chen <notifications@github.com> wrote:
```

 Thanks for your submission. Because we merge others' pull requests, there is a conflict in zk.xml. Please resolve the conflict and send another pull request again.—

**Comment by hawkchen** [comment]
Yes. I have resolved the conflict and merge your pull request. :)

**Pull request merged**
